const drafAxialFanOptions = [
  { model: "200", amount: 9203, price: "92,03 €", bgn: "180,00 BGN" },
  { model: "250", amount: 10226, price: "102,26 €", bgn: "200,00 BGN" },
  { model: "300", amount: 11248, price: "112,48 €", bgn: "220,00 BGN" },
  { model: "350", amount: 12782, price: "127,82 €", bgn: "250,00 BGN" },
];

const drafAxialFanProduct = {
  name: "Ventilateur axial DRAF",
  slug: "ventilateur-axial-draf",
  category: "Ventilateurs axiaux",
  amount: 9203,
  price: "92,03 €",
  description: "Ventilateur axial DRAF pour extraction et brassage d'air. Construction compacte avec grille métallique de protection et hélice axiale. Choisissez le diamètre adapté dans les options.",
  options: drafAxialFanOptions.map(({ model, amount, price, bgn }) => ({
    label: model,
    value: model.toLowerCase(),
    slug: `ventilateur-axial-draf-${model.toLowerCase()}`,
    amount,
    price,
    bgn,
  })),
  imageKey: "axialFanDraf",
  imageUrl: "",
  imageData: "",
  featured: true,
  active: true,
  sortOrder: 11,
};

const ysaAxialFanOptions = [
  { model: "250-2M", amount: 11760, price: "117,60 €", bgn: "230,00 BGN" },
  { model: "250-2T", amount: 11760, price: "117,60 €", bgn: "230,00 BGN" },
  { model: "250-4M", amount: 11760, price: "117,60 €", bgn: "230,00 BGN" },
  { model: "250-4T", amount: 11760, price: "117,60 €", bgn: "230,00 BGN" },
  { model: "300-2M", amount: 12782, price: "127,82 €", bgn: "250,00 BGN" },
  { model: "300-2T", amount: 12782, price: "127,82 €", bgn: "250,00 BGN" },
  { model: "300-4M", amount: 12782, price: "127,82 €", bgn: "250,00 BGN" },
  { model: "300-4T", amount: 12782, price: "127,82 €", bgn: "250,00 BGN" },
  { model: "350-M", amount: 13805, price: "138,05 €", bgn: "270,00 BGN" },
  { model: "350-T", amount: 13805, price: "138,05 €", bgn: "270,00 BGN" },
  { model: "400-M", amount: 14827, price: "148,27 €", bgn: "290,00 BGN" },
  { model: "400-T", amount: 14827, price: "148,27 €", bgn: "290,00 BGN" },
  { model: "450-M", amount: 16873, price: "168,73 €", bgn: "330,00 BGN" },
  { model: "450-T", amount: 16873, price: "168,73 €", bgn: "330,00 BGN" },
  { model: "500-M", amount: 18407, price: "184,07 €", bgn: "360,00 BGN" },
  { model: "500-T", amount: 18407, price: "184,07 €", bgn: "360,00 BGN" },
  { model: "550-M", amount: 19429, price: "194,29 €", bgn: "380,00 BGN" },
  { model: "550-T", amount: 19429, price: "194,29 €", bgn: "380,00 BGN" },
  { model: "600-M", amount: 21474, price: "214,74 €", bgn: "420,00 BGN" },
  { model: "600-T", amount: 21474, price: "214,74 €", bgn: "420,00 BGN" },
];

const ysaAxialFanProduct = {
  name: "Ventilateur axial YSA",
  slug: "ventilateur-axial-ysa",
  category: "Ventilateurs axiaux",
  amount: 11760,
  price: "117,60 €",
  description: "Ventilateur axial YSA pour extraction et brassage d'air. Corps bleu avec hélice rouge et grille métallique de protection. Choisissez le modèle adapté dans les options.",
  options: ysaAxialFanOptions.map(({ model, amount, price, bgn }) => ({
    label: model,
    value: model.toLowerCase(),
    slug: `ventilateur-axial-ysa-${model.toLowerCase()}`,
    amount,
    price,
    bgn,
  })),
  imageKey: "axialFanYsa",
  imageUrl: "",
  imageData: "",
  featured: true,
  active: true,
  sortOrder: 12,
};

const ksaAxialFanOptions = [
  { model: "250-2M", amount: 14316, price: "143,16 €", bgn: "280,00 BGN" },
  { model: "250-2T", amount: 14316, price: "143,16 €", bgn: "280,00 BGN" },
  { model: "250-4M", amount: 14316, price: "143,16 €", bgn: "280,00 BGN" },
  { model: "250-4T", amount: 14316, price: "143,16 €", bgn: "280,00 BGN" },
  { model: "300-2M", amount: 14827, price: "148,27 €", bgn: "290,00 BGN" },
  { model: "300-2T", amount: 14827, price: "148,27 €", bgn: "290,00 BGN" },
  { model: "300-4M", amount: 14827, price: "148,27 €", bgn: "290,00 BGN" },
  { model: "300-4T", amount: 14827, price: "148,27 €", bgn: "290,00 BGN" },
  { model: "350-M", amount: 16361, price: "163,61 €", bgn: "320,00 BGN" },
  { model: "350-T", amount: 16361, price: "163,61 €", bgn: "320,00 BGN" },
  { model: "400-M", amount: 17895, price: "178,95 €", bgn: "350,00 BGN" },
  { model: "400-T", amount: 17895, price: "178,95 €", bgn: "350,00 BGN" },
  { model: "450-M", amount: 18918, price: "189,18 €", bgn: "370,00 BGN" },
  { model: "450-T", amount: 18918, price: "189,18 €", bgn: "370,00 BGN" },
  { model: "500-M", amount: 20963, price: "209,63 €", bgn: "410,00 BGN" },
  { model: "500-T", amount: 20963, price: "209,63 €", bgn: "410,00 BGN" },
  { model: "550-M", amount: 21474, price: "214,74 €", bgn: "420,00 BGN" },
  { model: "550-T", amount: 21474, price: "214,74 €", bgn: "420,00 BGN" },
  { model: "600-M", amount: 23008, price: "230,08 €", bgn: "450,00 BGN" },
  { model: "600-T", amount: 23008, price: "230,08 €", bgn: "450,00 BGN" },
];

const ksaAxialFanProduct = {
  name: "Ventilateur axial KSA",
  slug: "ventilateur-axial-ksa",
  category: "Ventilateurs axiaux",
  amount: 14316,
  price: "143,16 €",
  description: "Ventilateur axial KSA pour montage mural et extraction d'air. Cadre carré bleu avec hélice rouge et grille métallique de protection. Choisissez le modèle adapté dans les options.",
  options: ksaAxialFanOptions.map(({ model, amount, price, bgn }) => ({
    label: model,
    value: model.toLowerCase(),
    slug: `ventilateur-axial-ksa-${model.toLowerCase()}`,
    amount,
    price,
    bgn,
  })),
  imageKey: "axialFanKsa",
  imageUrl: "",
  imageData: "",
  featured: true,
  active: true,
  sortOrder: 13,
};

const ktaAxialFanOptions = [
  { model: "160", amount: 4602, price: "46,02 €", bgn: "90,00 BGN" },
  { model: "200", amount: 5113, price: "51,13 €", bgn: "100,00 BGN" },
  { model: "250", amount: 5624, price: "56,24 €", bgn: "110,00 BGN" },
];

const ktaAxialFanProduct = {
  name: "Ventilateur axial KTA",
  slug: "ventilateur-axial-kta",
  category: "Ventilateurs axiaux",
  amount: 4602,
  price: "46,02 €",
  description: "Ventilateur axial KTA pour extraction d'air. Corps rond blanc avec hélice rouge et raccord arrière noir. Choisissez le diamètre adapté dans les options.",
  options: ktaAxialFanOptions.map(({ model, amount, price, bgn }) => ({
    label: model,
    value: model.toLowerCase(),
    slug: `ventilateur-axial-kta-${model.toLowerCase()}`,
    amount,
    price,
    bgn,
  })),
  imageKey: "axialFanKta",
  imageUrl: "",
  imageData: "",
  featured: true,
  active: true,
  sortOrder: 14,
};

const ykaDuctFanOptions = [
  { model: "100-A", amount: 7669, price: "76,69 €", bgn: "150,00 BGN" },
  { model: "100-B", amount: 7669, price: "76,69 €", bgn: "150,00 BGN" },
  { model: "125-A", amount: 8181, price: "81,81 €", bgn: "160,00 BGN" },
  { model: "125-B", amount: 8181, price: "81,81 €", bgn: "160,00 BGN" },
  { model: "150-A", amount: 8181, price: "81,81 €", bgn: "160,00 BGN" },
  { model: "150-B", amount: 8436, price: "84,36 €", bgn: "165,00 BGN" },
  { model: "160-A", amount: 8692, price: "86,92 €", bgn: "170,00 BGN" },
  { model: "160-B", amount: 8948, price: "89,48 €", bgn: "175,00 BGN" },
  { model: "200-A", amount: 10993, price: "109,93 €", bgn: "215,00 BGN" },
  { model: "200-B", amount: 11504, price: "115,04 €", bgn: "225,00 BGN" },
  { model: "250-A", amount: 13038, price: "130,38 €", bgn: "255,00 BGN" },
  { model: "250-B", amount: 13549, price: "135,49 €", bgn: "265,00 BGN" },
  { model: "315-A", amount: 15594, price: "155,94 €", bgn: "305,00 BGN" },
  { model: "315-B", amount: 16106, price: "161,06 €", bgn: "315,00 BGN" },
];

const ykaDuctFanProduct = {
  name: "Ventilateur de canal YKA",
  slug: "ventilateur-de-canal-yka",
  category: "Ventilateurs de canaux",
  amount: 7669,
  price: "76,69 €",
  description: "Ventilateur de canal YKA pour réseaux de ventilation. Corps métallique compact avec turbine centrifuge et boîtier de raccordement. Choisissez le modèle adapté dans les options.",
  options: ykaDuctFanOptions.map(({ model, amount, price, bgn }) => ({
    label: model,
    value: model.toLowerCase(),
    slug: `ventilateur-de-canal-yka-${model.toLowerCase()}`,
    amount,
    price,
    bgn,
  })),
  imageKey: "ductFanYka",
  imageUrl: "",
  imageData: "",
  featured: true,
  active: true,
  sortOrder: 21,
};

export const defaultShopProducts = [
  {
    name: "Ventilateurs axiaux",
    slug: "ventilateurs-axiaux",
    category: "Ventilation industrielle",
    amount: 24900,
    description: "Ventilateurs haute performance pour le renouvellement d'air et l'extraction.",
    imageKey: "axialFan",
    imageUrl: "",
    imageData: "",
    featured: true,
    active: true,
    sortOrder: 10,
  },
  drafAxialFanProduct,
  ysaAxialFanProduct,
  ksaAxialFanProduct,
  ktaAxialFanProduct,
  {
    name: "Ventilateurs de canaux",
    slug: "ventilateurs-de-canaux",
    category: "Réseaux de conduits",
    amount: 18900,
    description: "Solutions compactes pour installations dans les conduits.",
    imageKey: "ductFan",
    imageUrl: "",
    imageData: "",
    featured: true,
    active: true,
    sortOrder: 20,
  },
  ykaDuctFanProduct,
  {
    name: "Moteur électrique monophasé 1,1 kW 2800 tr/min",
    slug: "moteur-electrique-monophase-11-kw-2800-tr-min",
    category: "Moteurs électriques 220/380",
    amount: 9500,
    description: "Moteur électrique monophasé VOSTOK MOTORS 1,1 kW / 2800 tr/min, alimentation 230 V ±5 % et fréquence 50 Hz. Boîtier en aluminium, deux condensateurs, résistance en aluminium, rondelle à double canal, prise et câble inclus. Poids 11 kg.",
    imageKey: "electricMotor11Kw2800Aluminum",
    imageUrl: "",
    imageData: "",
    featured: true,
    active: true,
    sortOrder: 50,
  },
  {
    name: "Moteur électrique monophasé 1,1 kW 2800 tr/min carter en fonte",
    slug: "moteur-electrique-monophase-11-kw-2800-tr-min-carter-en-fonte",
    category: "Moteurs électriques 220/380",
    amount: 8500,
    description: "Moteur électrique monophasé VOSTOK MOTORS 1,1 kW / 2800 tr/min, alimentation 230 V ±5 % et fréquence 50 Hz. Carter en fonte, deux condensateurs, résistance en aluminium, rondelle à double canal, prise et câble inclus. Poids 15 kg.",
    imageKey: "electricMotor",
    imageUrl: "",
    imageData: "",
    featured: true,
    active: true,
    sortOrder: 51,
  },
  {
    name: "Moteur électrique monophasé 2,2 kW 2800 tr/min",
    slug: "moteur-electrique-monophase-22-kw-2800-tr-min",
    category: "Moteurs électriques 220/380",
    amount: 11500,
    description: "Moteur électrique monophasé VOSTOK MOTORS 2,2 kW / 2800 tr/min, alimentation 230 V ±5 % et fréquence 50 Hz. Boîtier en aluminium, deux condensateurs, résistance en aluminium, rondelle à double canal, câble et prise inclus. Poids 18 kg.",
    imageKey: "electricMotor22Kw",
    imageUrl: "",
    imageData: "",
    featured: true,
    active: true,
    sortOrder: 52,
  },
  {
    name: "Moteur électrique monophasé 2,2 kW 2800 tr/min carter en fonte",
    slug: "moteur-electrique-monophase-22-kw-2800-tr-min-carter-en-fonte",
    category: "Moteurs électriques 220/380",
    amount: 11500,
    description: "Moteur électrique monophasé VOSTOK MOTORS 2,2 kW / 2800 tr/min, alimentation 230 V ±5 % et fréquence 50 Hz. Étui en fonte, deux condensateurs, résistance en aluminium, rondelle à double canal, prise et câble inclus. Poids 23 kg.",
    imageKey: "electricMotor22Kw2800CastIron",
    imageUrl: "",
    imageData: "",
    featured: true,
    active: true,
    sortOrder: 53,
  },
  {
    name: "Moteur électrique monophasé 2,2 kW 2800 tr/min carter en fonte enroulement cuivre",
    slug: "moteur-electrique-monophase-22-kw-2800-tr-min-carter-en-fonte-enroulement-cuivre",
    category: "Moteurs électriques 220/380",
    amount: 14500,
    description: "Moteur électrique monophasé VOSTOK MOTORS 2,2 kW / 2800 tr/min, alimentation 230 V ±5 % et fréquence 50 Hz. Étui en fonte, deux condensateurs, enroulement en cuivre, rondelle à double canal, prise et câble inclus. Poids 24 kg.",
    imageKey: "electricMotor22Kw2800CastIronCopper",
    imageUrl: "",
    imageData: "",
    featured: true,
    active: true,
    sortOrder: 54,
  },
  {
    name: "Moteur électrique monophasé 2,2 kW 1430 tr/min carter en fonte",
    slug: "moteur-electrique-monophase-22-kw-1430-tr-min-carter-en-fonte",
    category: "Moteurs électriques 220/380",
    amount: 11500,
    description: "Moteur électrique monophasé VOSTOK MOTORS 2,2 kW / 1430 tr/min, alimentation 230 V ±5 % et fréquence 50 Hz. Étui en fonte, deux condensateurs, résistance en aluminium, rondelle à double canal, prise et câble inclus. Poids 30 kg.",
    imageKey: "electricMotor22Kw1430CastIron",
    imageUrl: "",
    imageData: "",
    featured: true,
    active: true,
    sortOrder: 55,
  },
  {
    name: "Moteur électrique monophasé 3 kW 1430 tr/min en fonte",
    slug: "moteur-electrique-monophase-3-kw-1430-tr-min-en-fonte",
    category: "Moteurs électriques 220/380",
    amount: 14900,
    description: "Moteur électrique monophasé VOSTOK MOTORS 3 kW / 1430 tr/min, alimentation 230 V ±5 % et fréquence 50 Hz. Étui en fonte, deux condensateurs, résistance en aluminium, rondelle à double canal, prise et câble inclus. Poids 30 kg.",
    imageKey: "electricMotor3Kw1430CastIron",
    imageUrl: "",
    imageData: "",
    featured: true,
    active: true,
    sortOrder: 56,
  },
  {
    name: "Moteur électrique triphasé 1,1 kW 2850 tr/min",
    slug: "moteur-electrique-triphase-11-kw-2850-tr-min",
    category: "Moteurs électriques triphasés",
    amount: 9500,
    description: "Moteur électrique triphasé VOSTOK MOTORS 1,1 kW / 2850 tr/min, alimentation 380 V et fréquence 50 Hz. Boîtier en aluminium, résistance en aluminium et rondelle à double canal incluse. Poids 11 kg.",
    imageKey: "electricMotorThreePhase11Kw2850",
    imageUrl: "",
    imageData: "",
    featured: true,
    active: true,
    sortOrder: 57,
  },
  {
    name: "Moteur électrique triphasé 2,2 kW 1430 tr/min",
    slug: "moteur-electrique-triphase-22-kw-1430-tr-min",
    category: "Moteurs électriques triphasés",
    amount: 13900,
    description: "Moteur électrique triphasé VOSTOK MOTORS 2,2 kW / 1430 tr/min, alimentation 380 V et fréquence 50 Hz. Étui en fonte, enroulement 100 % cuivre et rondelle à double canal incluse. Poids 23 kg.",
    imageKey: "electricMotorThreePhase22Kw1430CastIronCopper",
    imageUrl: "",
    imageData: "",
    featured: true,
    active: true,
    sortOrder: 58,
  },
  {
    name: "Moteur électrique triphasé 3 kW 1430 tr/min",
    slug: "moteur-electrique-triphase-3-kw-1430-tr-min",
    category: "Moteurs électriques triphasés",
    amount: 14900,
    description: "Moteur électrique triphasé VOSTOK 3 kW / 1430 tr/min, alimentation 380 V et fréquence 50 Hz. Étui en fonte, résistance en aluminium et rondelle à double canal incluse. Poids 30 kg.",
    imageKey: "electricMotorThreePhase3Kw1430CastIron",
    imageUrl: "",
    imageData: "",
    featured: true,
    active: true,
    sortOrder: 59,
  },
  {
    name: "Moteur électrique triphasé 2,2 kW 2850 tr/min",
    slug: "moteur-electrique-triphase-22-kw-2850-tr-min",
    category: "Moteurs électriques triphasés",
    amount: 13900,
    description: "Moteur électrique triphasé VOSTOK 2,2 kW / 2850 tr/min, alimentation 380 V et fréquence 50 Hz. Étui en fonte, enroulement 100 % cuivre et rondelle à double canal incluse. Poids 23 kg.",
    imageKey: "electricMotorThreePhase22Kw2850CastIronCopper",
    imageUrl: "",
    imageData: "",
    featured: true,
    active: true,
    sortOrder: 60,
  },
  {
    name: "Moteur électrique triphasé 3 kW 2850 tr/min",
    slug: "moteur-electrique-triphase-3-kw-2850-tr-min",
    category: "Moteurs électriques triphasés",
    amount: 14900,
    description: "Moteur électrique triphasé VOSTOK 3 kW / 2850 tr/min, alimentation 380 V et fréquence 50 Hz. Étui en fonte, résistance en aluminium et rondelle à double canal incluse. Poids 30 kg.",
    imageKey: "electricMotorThreePhase3Kw2850CastIron",
    imageUrl: "",
    imageData: "",
    featured: true,
    active: true,
    sortOrder: 61,
  },
  {
    name: "Moteur électrique triphasé 5,5 kW 2850 tr/min",
    slug: "moteur-electrique-triphase-55-kw-2850-tr-min",
    category: "Moteurs électriques triphasés",
    amount: 32500,
    description: "Moteur électrique triphasé VOSTOK 5,5 kW / 2850 tr/min, alimentation 380 V et fréquence 50 Hz. Boîtier en aluminium, enroulement 100 % cuivre et rondelle à double canal incluse. Poids 47 kg.",
    imageKey: "electricMotorThreePhase55Kw2850AluminumCopper",
    imageUrl: "",
    imageData: "",
    featured: true,
    active: true,
    sortOrder: 62,
  },
  {
    name: "Grilles de ventilation plafond",
    slug: "grilles-de-ventilation-plafond",
    category: "Diffusion d'air",
    amount: 7900,
    description: "Diffusion d'air efficace pour bureaux, commerces et bâtiments industriels.",
    imageKey: "ceilingGrille",
    imageUrl: "",
    imageData: "",
    featured: false,
    active: true,
    sortOrder: 70,
  },
  {
    name: "Régulateurs",
    slug: "regulateurs",
    category: "Pilotage",
    amount: 12900,
    description: "Régulation de vitesse et contrôle pour optimiser vos installations.",
    imageKey: "speedController",
    imageUrl: "",
    imageData: "",
    featured: true,
    active: true,
    sortOrder: 80,
  },
];

export const defaultShopCategories = Array.from(
  new Set([
    "Accessoires",
    "Grille de ventilation plafond",
    "Moteurs électriques 220/380",
    "Pompes à eau",
    "Portes d'entrée et blindées",
    "Regulateurs",
    "Ventilateurs axiaux",
    "Ventilateurs de canaux",
    "Ventilateurs de centrifuges",
    "Ventilateurs de restaurant",
    "Ventilateurs de salle de bains",
    "Ventilateurs de toiture",
    ...defaultShopProducts.map((product) => product.category),
  ]),
);

export const allowedImageKeys = new Set([
  "axialFan",
  "axialFanDraf",
  "axialFanYsa",
  "axialFanKsa",
  "axialFanKta",
  "ductFan",
  "ductFanYka",
  "ceilingGrille",
  "speedController",
  "electricMotor",
  "electricMotor11Kw2800Aluminum",
  "electricMotor22Kw",
  "electricMotor22Kw1430CastIron",
  "electricMotor22Kw2800CastIron",
  "electricMotor22Kw2800CastIronCopper",
  "electricMotor3Kw1430CastIron",
  "electricMotorThreePhase11Kw2850",
  "electricMotorThreePhase22Kw1430CastIronCopper",
  "electricMotorThreePhase22Kw2850CastIronCopper",
  "electricMotorThreePhase3Kw1430CastIron",
  "electricMotorThreePhase3Kw2850CastIron",
  "electricMotorThreePhase55Kw2850AluminumCopper",
]);
