export const defaultShopProducts = [
  {
    name: "Ventilateurs axiaux",
    slug: "ventilateurs-axiaux",
    category: "Ventilation industrielle",
    amount: 24900,
    description: "Ventilateurs haute performance pour le renouvellement d'air et l'extraction.",
    imageKey: "axialFan",
    imageUrl: "",
    featured: true,
    active: true,
    sortOrder: 10,
  },
  {
    name: "Ventilateurs de canaux",
    slug: "ventilateurs-de-canaux",
    category: "Réseaux de conduits",
    amount: 18900,
    description: "Solutions compactes pour installations dans les conduits.",
    imageKey: "ductFan",
    imageUrl: "",
    featured: true,
    active: true,
    sortOrder: 20,
  },
  {
    name: "Grilles de ventilation plafond",
    slug: "grilles-de-ventilation-plafond",
    category: "Diffusion d'air",
    amount: 7900,
    description: "Diffusion d'air efficace pour bureaux, commerces et bâtiments industriels.",
    imageKey: "ceilingGrille",
    imageUrl: "",
    featured: false,
    active: true,
    sortOrder: 30,
  },
  {
    name: "Régulateurs",
    slug: "regulateurs",
    category: "Pilotage",
    amount: 12900,
    description: "Régulation de vitesse et contrôle pour optimiser vos installations.",
    imageKey: "speedController",
    imageUrl: "",
    featured: true,
    active: true,
    sortOrder: 40,
  },
];

export const defaultShopCategories = Array.from(
  new Set([
    "Accessoires",
    "Grille de ventilation plafond",
    "Moteurs électriques 220/380",
    "Pompes à eau",
    "Portes d'entrée et blindées",
    "Regulateurs",
    "Ventilateurs axiaux",
    "Ventilateurs de canaux",
    "Ventilateurs de centrifuges",
    "Ventilateurs de restaurant",
    "Ventilateurs de salle de bains",
    "Ventilateurs de toiture",
    ...defaultShopProducts.map((product) => product.category),
  ]),
);

export const allowedImageKeys = new Set(["axialFan", "ductFan", "ceilingGrille", "speedController"]);
